export const GET_POSTS = 'GET_POSTS';
export const GET_USER = 'GET_USER';

export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_SIGNIN_REQUEST = 'AUTH_SIGNIN_REQUEST';
export const AUTH_SIGNIN_FAILURE = 'AUTH_SIGNIN_FAILURE';

export const SIGN_UP_LOCAL = 'SIGN_UP_LOCAL' ;
export const SIGN_UP_LOCAL_SUCCESSFUL = 'SIGN_UP_LOCAL_SUCCESSFUL';
export const SIGN_UP_LOCAL_FAILURE = 'SIGN_UP_LOCAL_FAILURE'

export const SIGN_IN_GOOGLE = 'SIGN_IN_GOOGLE';
export const SIGN_IN_GOOGLE_SUCCESSFUL = 'SIGN_IN_GOOGLE_SUCCESSFUL';
export const SIGN_IN_GOOGLE_FAILURE = 'SIGN_IN_GOOGLE_FAILURE';

export const SIGN_IN_LOCAL = 'SIGN_IN_LOCAL';
export const SIGN_IN_LOCAL_SUCCESSFUL = 'SIGN_IN_LOCAL_SUCCESSFUL';
export const SIGN_IN_LOCAL_FAILURE = 'SIGN_IN_LOCAL_FAILURE';

export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESSFUL = 'SIGN_OUT_SUCCESSFUL';
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESSFUL = 'CREATE_POST_SUCCESSFUL';
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESSFUL = 'FETCH_POSTS_SUCCESSFUL';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_SUCCESSFUL = 'FETCH_POST_SUCCESSFUL';
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE';

export const EDIT_POST = 'EDIT_POST';
export const EDIT_POST_SUCCESSFUL = 'EDIT_POST_SUCCESSFUL';
export const EDIT_POST_FAILURE = 'EDIT_POST_FAILURE';